database:
  host: 192.168.2.190
  port: 35432
  user: postgres
  password: SLBpg2025
  dbname: knowledge_base
  sslmode: disable

minio:
  endpoint: 192.168.2.190:39000
  accessKeyID: admin
  secretAccessKey: admin@2025
  useSSL: false
  bucketName: knowledge-bucket

server:
  port: ":8080"